Homework 5
eugene-okulik/Klinovuy pull request #4
Opened 2024-12-05 17:00 UTC by Klinovuy

2024-12-05 17:15 UTC, Klinovuy commented
Если всё правильно, то прошу открыть ещё один урок

2024-12-06 06:40 UTC, eugene-okulik requested changes

2024-12-06 06:40 UTC, eugene-okulik commented on homework/daniil_katkov/homework_5/task_2.py
> +result_for_1 = result_1.index('42')
Если еще в момент написания программы мы знаем, что в строке будет число 42, то мы можем написать просто print(42 + 10)  
Заморочка в том, чтобы найти в этой строке число, каким бы оно там ни было. Для этого нужно найти в этих строках что-то одинаковое: количество символов перед числом разное; количество символов в числе тоже разное. Но есть в структуре всех строк что-то одинаковое и на это можно опереться.  
В примерах - варианты того, как может ответить программа. Вместо числа 42 может оказаться число 28346473, вместо 514 число 3. Нам нужно сделать один код, который сможет работать с любым из вариантов ответа. То есть обработать каждую переменную абсолютно одинаковым кодом. Пока что делаем это копируя код, потом будем учиться как избежать здесь этого копирования.

2024-12-06 10:38 UTC, Klinovuy commented on homework/daniil_katkov/homework_5/task_2.py
> +result_for_1 = result_1.index('42')
"Пока что делаем это копируя код, потом будем учиться как избежать здесь этого копирования." - какой код надо копировать? Я не очень понял, что мне надо сделать исходя из этого комментария. Надо написать универсальный код?

2024-12-06 14:45 UTC, Klinovuy commented
Исходя из требований, что надо использовать index и срез, ты я не могу придумать другой способ, как это сделать

2024-12-07 08:52 UTC, eugene-okulik approved these changes

2024-12-07 08:52 UTC, eugene-okulik commented on homework/daniil_katkov/homework_5/task_2.py
> +int_result_1 = int(result_1[result_for_1:]) + 10
"как смог" - это ровно то, "как надо" )))  
Теперь у тебя код универсальный и сможет получить из этой строки любое число, а потом эти числом воспользоваться. А раньше твой код мог получить только числа 42, 514 и 9

2024-12-07 08:52 UTC, merged